version: '3.7'

services:
    kittybot:
        image: kittybot/kittybot:latest
        container_name: kittybot
        restart: unless-stopped
        env_file:
            - conf.env
        environment:
            - ENV=PRODUCTION
        volumes:
            - ./config.json:/home/kittybot/config.json
        networks:
            - database
            - lavalink
            - traefik
        expose:
            - 6969
        depends_on:
            - lavalink
        labels:
            io.portainer.accesscontrol.teams: kittybot
            traefik.enable: true
            traefik.http.routers.api.rule: Host(`api.$PRIMARY_DOMAIN`) || Host(`$PRIMARY_DOMAIN/api`)
            traefik.http.middlewares.api-rewrite.stripprefix.prefixes: /api
            traefik.http.routers.api.entrypoints: https
            traefik.http.services.api.loadbalancer.server.port: 6969
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:6969/health_check']
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    website:
        image: kittybot/kittybot-website:latest
        container_name: kittybot_website
        restart: unless-stopped
        networks:
            - traefik
        expose:
            - 80
        depends_on:
            - kittybot
        labels:
            io.portainer.accesscontrol.teams: kittybot
            traefik.enable: true
            traefik.http.routers.website.rule: Host(`$PRIMARY_DOMAIN`) || Host(`www.$PRIMARY_DOMAIN`)
            traefik.http.routers.website.entrypoints: https
            traefik.http.routers.website.middlewares: www-website-redirect
            traefik.http.services.website.loadbalancer.server.port: 80
            traefik.http.middlewares.www-website-redirect.redirectregex.regex: https://www.$PRIMARY_DOMAIN/(.*)
            traefik.http.middlewares.www-website-redirect.redirectregex.replacement: https://$PRIMARY_DOMAIN/$${1}
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:80']
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    lavalink:
        image: fredboat/lavalink:dev
        container_name: lavalink_1
        restart: unless-stopped
        command: -Xmx128m
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - lavalink
        expose:
            - 2333
        labels:
            io.portainer.accesscontrol.teams: kittybot
    lavalink-dev:
        image: fredboat/lavalink:dev
        container_name: lavalink_dev
        restart: unless-stopped
        command: -Xmx64m
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        volumes:
            - ./application-dev.yml:/opt/Lavalink/application.yml
        networks:
            - lavalink
        expose:
            - 2333
        ports:
            - 2333:2333

networks:
    lavalink:
        name: lavalink
    database:
        external: true
    traefik:
        external: true
