version: '3.7'

services:
    database:
        image: 5c0cc51367ea
        container_name: database
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        env_file:
            - conf.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - database
        expose:
            - 5432
    database-dev:
        image: 5c0cc51367ea
        container_name: database-dev
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        env_file:
            - conf-dev.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4:4
        container_name: pgadmin
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./.data/pgadmin:/var/lib/pgadmin
        networks:
            - pgadmin
            - database
            - traefik
        expose:
            - 80
        labels:
            traefik.enable: true
            traefik.http.routers.pgadmin.rule: Host(`pgadmin.$PRIMARY_DOMAIN`)
            traefik.http.routers.pgadmin.entrypoints: https
            traefik.http.services.pgadmin.loadbalancer.server.port: 80

networks:
    database:
        name: database
    pgadmin:
        name: pgadmin
    traefik:
        external: true
