version: '3.7'

services:
    portainer:
        image: portainer/portainer-ce:alpine
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.data:/data
        networks:
            - portainer
            - traefik
        expose:
            - 9000
        ports:
            - 8000:8000
        labels:
            traefik.enable: true
            traefik.http.routers.portainer.rule: Host(`portainer.$PRIMARY_DOMAIN`)
            traefik.http.routers.portainer.entrypoints: https
            traefik.http.services.portainer.loadbalancer.server.port: 9000

networks:
    portainer:
        name: portainer
    traefik:
        external: true
